---
- name: Include fleet
  include_tasks: fleet.yml
  tags: nix_fleet
  when: 'nix_fleet'

- name: Include Rsyslog
  include_tasks: rsyslog.yml
  tags: nix_rsyslog
  when: 'nix_rsyslog'

- name: Include wazuh
  include_tasks: wazuh.yml
  tags: nix_wazuh
  when: 'nix_wazuh'
